### ISSUE TITLE
U4B shows wrong  Locatorprefix

### ISSUE THREAD

**Issue by whallmann** [EngineerGuy314/pico-WSPRer#13]
I watched on the console with verbose 5 a strange thing .
The locator is some kind of mismatch. See hardcopy please
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/5610320/1c64ef6c-0cdf-4f56-8767-69b8f24f1a28)

that may be the reason why not the correct locators are received at
https://traquito.github.io/search/spots/dashboard/?band=20m&channel=493&callsign=DF7PN&dtGte=2024-03-24&dtLte=
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/5610320/84d7fc1d-d456-48ca-84a7-bca881eefd44)

**Comment by EngineerGuy314** [comment]
interesting.  One question, when you saw the terminal show JN49u?? was that the same transmission that the website recorded as BB00AV? or was that a different occurence?

**Comment by whallmann** [comment]
Oh, dont remember excactly.
If i look to the traquita site. all my transmissions are same bad locator
today. I only saw this one and made foto. maybe this bad line was steady.
cant check it now because auf little fieldday.
making aurora dx qsos on 2 mtr.

73 wolf

EngineerGuy314 ***@***.***> schrieb am Sa., 11. Mai 2024,
15:42:

**Comment by EngineerGuy314** [comment]
OK, i am about 90% sure i fixed it (forgot to null terminate a string).  I will close this issue, please feel free to open a new one if still no good. The link and screenshots you post are extremely helpful in tracking down these gremlins!

**Comment by whallmann** [comment]
Yes Rob. Thanks to you and good bye to the gremlins 😁

EngineerGuy314 ***@***.***> schrieb am Sa., 11. Mai 2024,
19:58:
