### ISSUE TITLE
GPS fix, but getting wrong grid square.

### ISSUE THREAD

**Issue by WildMany** [EngineerGuy314/pico-WSPRer#14]
Tried on laptop, tried on battery (power bank), and during two hours, not a single correct gridsquare (JN95):
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/18058158/ee200e42-d6b2-4469-8329-b56780aae914)

Meanwhile, during this period assembled ICT tracker:
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/18058158/3f79af34-400a-4d76-9bb5-854e9a10f211)
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/18058158/1b67de0f-9c0e-4ea9-9f5a-f53fe877c420)
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/18058158/17b122e9-b649-4afc-b53f-77798923dd83)

RPi Pico tracker should be easy and fast to set, but it is not so easy.

73, Milan, 9A4GE.

P.S. It has GPS fix, but it shows it on Antartic.:
![image](https://github.com/EngineerGuy314/pico-WSPRer/assets/18058158/40636189-49c5-483f-8fd3-c4aa46069b1b)

**Comment by EngineerGuy314** [comment]
this may have been fixed by the change I just pushed for Whallmann. if the current version still doesnt work please turn verbosity to 5 and try to capture some of the debug messages.

**Comment by WildMany** [comment]
Now seems that it working just fine: JN95JG. Will test in next few hours.

73, Milan, 9A4GE
