### ISSUE TITLE
last uf2-build not working?

### ISSUE THREAD

**Issue by marcels1990** [EngineerGuy314/pico-WSPRer#17]
Hello,

today i set up a tracker and i tried to copy the last build (https://github.com/EngineerGuy314/pico-WSPRer/blob/main/build/pico-WSPRer.uf2) to the pico but it does not reboot. Is there an error in the build?
i tried some other uf2 examples and these file worked fine.

thank you very much and many thanks for the wonderful project
73 IN3IZL

**Comment by marcels1990** [comment]
the pico does not reboot after i copy the file. There is no LED activity and the COM-Port does not show up.

**Comment by EngineerGuy314** [comment]
no way to debug without the serial port. email me the .uf2 that you downloaded and I will take a look.

**Comment by marcels1990** [comment]
this is the file i am using, i had to make a zip to upload it

**Comment by marcels1990** [comment]
ok problem solved, now i tried to download the file directly from github (raw).
First i was downloading it with "wget https://github.com/EngineerGuy314/pico-WSPRer/blob/main/build/pico-WSPRer.uf2" but after downloading it via the raw button it worked.
thank you very much
