### ISSUE TITLE
RMC Sentence with other prefix here

### ISSUE THREAD

**Issue by whallmann** [EngineerGuy314/pico-WSPRer#3]
In file _GPStime.c_  in function _GPStimeProcNMEAsentence_ there will be scanned to "**$GNRMC,**".
On other gps units the sentence starts with $**GPRMC**.
Maybe it is a good idea to scan both prefixes or use a wildcard? 
regards
Wolf

**Comment by sivaelid** [comment]
This would be a good fix for people  using different GPS, I would also need to be done with the GNGGA as well thats used  to cover GPGGA.

Simon G8HAM

**Comment by EngineerGuy314** [comment]
done. it will now accept either GN or GP prefixes for both RMC and GGA.
