### ISSUE TITLE
PCB request

### ISSUE THREAD

**Issue by marcels1990** [EngineerGuy314/pico-WSPRer#44]
Hello,

i was searching for other PCB-producers and the agent suggested to update the PCB design: the vias on the attached file should be moved away from SMD pads to guarantee assembly quality.
Can i send it in production as-is or does the gerberfile needs to be changed?

Thank you very much
MS

![Screenshot_20241023-114332](https://github.com/user-attachments/assets/9eab9604-9554-4c31-bf1d-2156186199be)

**Comment by EngineerGuy314** [comment]
This was my first time doing any PCB layout work, so I am open to any and all suggestions. 

I will move those vias and post updated gerbers. However, JLCPCB did produce me a batch of trackers based on the exact gerbers I put in the PCB folder, and they seem to work okay. I have not been able to flight test them yet though. (I did successfully flight test an earlier rev of my PCB design, that was slightly less congested).

**Comment by marcels1990** [comment]
Thank you very much, i will post the name of the other PCB-producer if the tests are ok
