### ISSUE TITLE
tranquito shows no Altitude?!

### ISSUE THREAD

**Issue by whallmann** [EngineerGuy314/pico-WSPRer#9]
My first ballon DF7PN with channel 493 is flying. I wonder why i see no Altitude (meanwhile Speed is known as GPSKPH).
I thought the EncPower is the aprox. Height level. 
Is it posible to calculate the Altitude anyway?

See here: https://traquito.github.io/search/spots/dashboard/?band=20m&channel=493&callsign=DF7PN&dtGte=2024-04-09&dtLte=
73 Wolf DF7PN

**Comment by EngineerGuy314** [comment]
i looked at your data, and I don't know how to explain that.
>>EncPower is the aprox. Height level.

that is only true for the Zachtek protocol, it looks like you are tracking it with U4B protocol

Did you use the latest version of the software?

In a previous version of the software if it loses GPS lock it will still transmit, and use the previous known location, but put in a zero for altitude. but that doesnt seem to be whats going on here

**Comment by EngineerGuy314** [comment]
i see you have the altitude reporting now, i will close this. Also want to explain the knots your seeing. The tracking websites usually figure out your speed pretty well based on change in position. So i am sneaking the number of satellites seen by the GPS into the knots field (the tracking websites multiply this by two unfortunately).  So basically that last spot where it reported 20 knots means your gps receiver was viewing 10 satellites.
![s](https://github.com/EngineerGuy314/pico-WSPRer/assets/123671395/a7205a8d-bb33-445a-9b7b-9068f72b2f5a)
